package core

import (
	"math"
	"sort"
	"strconv"
	"strings"
	"unicode/utf16"
)

// Hand-rolled canonical JSON serializer — port of canonical_json.rs /
// CanonicalJson.java. Reproduces JSON.stringify(sortKeys(v), null, 2) + "\n"
// byte-for-byte: recursively key-sorted objects, 2-space indent, LF + trailing
// newline, raw non-ASCII, control chars as \uXXXX.

// CanonicalStringify serializes value to canonical JSON, with a trailing "\n".
func CanonicalStringify(value Value) string {
	var b strings.Builder
	writeValue(&b, value, 0)
	b.WriteByte('\n')
	return b.String()
}

func writeValue(b *strings.Builder, value Value, depth int) {
	switch value.Kind {
	case KindNull:
		b.WriteString("null")
	case KindBool:
		if value.Bool {
			b.WriteString("true")
		} else {
			b.WriteString("false")
		}
	case KindInt:
		b.WriteString(strconv.FormatInt(value.Int, 10))
	case KindFloat:
		writeNumber(b, value.Float)
	case KindString:
		writeString(b, value.Str)
	case KindList:
		writeArray(b, value.List, depth)
	case KindMap:
		writeObject(b, value.Map, depth)
	}
}

func writeObject(b *strings.Builder, m map[string]Value, depth int) {
	if len(m) == 0 {
		b.WriteString("{}")
		return
	}
	// The goldens were generated by JS sort() / Java TreeMap, which order by
	// UTF-16 code units — replicate that rather than Go's UTF-8 byte order.
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Slice(keys, func(i, j int) bool {
		return compareUTF16(keys[i], keys[j]) < 0
	})
	b.WriteString("{\n")
	for i, key := range keys {
		indent(b, depth+1)
		writeString(b, key)
		b.WriteString(": ")
		writeValue(b, m[key], depth+1)
		if i+1 < len(keys) {
			b.WriteByte(',')
		}
		b.WriteByte('\n')
	}
	indent(b, depth)
	b.WriteByte('}')
}

func writeArray(b *strings.Builder, list []Value, depth int) {
	if len(list) == 0 {
		b.WriteString("[]")
		return
	}
	b.WriteString("[\n")
	for i, item := range list {
		indent(b, depth+1)
		writeValue(b, item, depth+1)
		if i+1 < len(list) {
			b.WriteByte(',')
		}
		b.WriteByte('\n')
	}
	indent(b, depth)
	b.WriteByte(']')
}

func writeString(b *strings.Builder, s string) {
	b.WriteByte('"')
	for _, c := range s {
		switch c {
		case '"':
			b.WriteString("\\\"")
		case '\\':
			b.WriteString("\\\\")
		case '\n':
			b.WriteString("\\n")
		case '\r':
			b.WriteString("\\r")
		case '\t':
			b.WriteString("\\t")
		case '\b':
			b.WriteString("\\b")
		case '\f':
			b.WriteString("\\f")
		default:
			if c < 0x20 {
				b.WriteString("\\u")
				hex := strconv.FormatInt(int64(c), 16)
				for k := len(hex); k < 4; k++ {
					b.WriteByte('0')
				}
				b.WriteString(hex)
			} else {
				// Non-ASCII (and all other) characters are emitted raw.
				b.WriteRune(c)
			}
		}
	}
	b.WriteByte('"')
}

func writeNumber(b *strings.Builder, d float64) {
	// A finite integral double serializes as an integer (matching JS
	// JSON.stringify and Rust's `d as i64`).
	if !math.IsNaN(d) && !math.IsInf(d, 0) && d == float64(int64(d)) {
		b.WriteString(strconv.FormatInt(int64(d), 10))
	} else {
		b.WriteString(strconv.FormatFloat(d, 'g', -1, 64))
	}
}

func indent(b *strings.Builder, depth int) {
	for i := 0; i < depth; i++ {
		b.WriteString("  ")
	}
}

// compareUTF16 compares two strings by their UTF-16 code-unit sequences.
func compareUTF16(a, b string) int {
	ua := utf16.Encode([]rune(a))
	ub := utf16.Encode([]rune(b))
	for i := 0; i < len(ua) && i < len(ub); i++ {
		if ua[i] != ub[i] {
			if ua[i] < ub[i] {
				return -1
			}
			return 1
		}
	}
	switch {
	case len(ua) < len(ub):
		return -1
	case len(ua) > len(ub):
		return 1
	default:
		return 0
	}
}
