package core

import (
	"os"
	"path/filepath"
	"sort"
	"testing"
)

// bundlesDir is the shared corpus, a sibling of go/ at the repo root.
func bundlesDir(t *testing.T) string {
	t.Helper()
	return filepath.Join("..", "..", "conformance", "bundles")
}

func bundleDirs(t *testing.T) []string {
	t.Helper()
	entries, err := os.ReadDir(bundlesDir(t))
	if err != nil {
		t.Fatalf("read bundles: %v", err)
	}
	var dirs []string
	for _, e := range entries {
		if e.IsDir() {
			dirs = append(dirs, filepath.Join(bundlesDir(t), e.Name()))
		}
	}
	sort.Strings(dirs)
	return dirs
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return string(b)
}

func TestDocMatchesGolden(t *testing.T) {
	for _, dir := range bundleDirs(t) {
		name := filepath.Base(dir)
		t.Run(name, func(t *testing.T) {
			source := readFile(t, filepath.Join(dir, "example.md"))
			doc := Parse("example.md", source)
			assertMatchesGolden(t, name, "doc.json", ToDocArtifact(doc), readFile(t, filepath.Join(dir, "golden", "doc.json")))
		})
	}
}

// assertMatchesGolden compares an artifact with a golden by CONTENT: the golden
// is one file, generated by the TypeScript reference, and what a port must agree
// on is what it says. Key order, indentation and escaping belong to whichever
// writer produced the file, not to the contract.
func assertMatchesGolden(t *testing.T, bundle, artifactName string, actual Value, goldenText string) {
	t.Helper()
	want, err := ParseJSONValue(goldenText)
	if err != nil {
		t.Fatalf("%s/%s is not valid JSON: %v", bundle, artifactName, err)
	}
	if !ValueEqual(actual, want) {
		t.Errorf("%s mismatch for %s\n--- got ---\n%#v\n--- want ---\n%#v", artifactName, bundle, actual, want)
	}
}
