using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using System.Text.Json;

namespace Varar.Core;

/// <summary>
/// Canonical JSON serializer — the byte-for-byte contract every port's goldens are
/// compared against. Port of the Rust <c>canonical_json.rs</c> / Java
/// <c>CanonicalJson</c>: reproduces <c>JSON.stringify(sortKeys(v), null, 2) + "\n"</c>
/// exactly — recursively key-sorted objects (UTF-16 code-unit order), 2-space
/// indent, LF + trailing newline, raw non-ASCII, control chars as <c>\uXXXX</c>,
/// integral doubles as integers.
/// <para>
/// Hand-rolled rather than configured on <c>System.Text.Json</c>, because
/// byte-exactness needs UTF-16 key ordering, integral-float-as-integer, and the
/// precise escaping set — the same reason the Java and Rust ports hand-roll.
/// </para>
/// </summary>
public static class CanonicalJson
{
    /// <summary>Serializes <paramref name="value"/> to canonical JSON with a trailing newline.</summary>
    public static string Stringify(Value value)
    {
        var sb = new StringBuilder();
        WriteValue(sb, value, 0);
        sb.Append('\n');
        return sb.ToString();
    }

    /// <summary>
    /// Parses JSON text into a <see cref="Value"/> tree (parsing needs no
    /// canonicalization, so it delegates to <see cref="JsonDocument"/>). Integral
    /// numbers become <see cref="VInt"/>, the rest <see cref="VFloat"/>.
    /// </summary>
    public static Value Parse(string json)
    {
        using var doc = JsonDocument.Parse(json);
        return FromElement(doc.RootElement);
    }

    private static Value FromElement(JsonElement element) => element.ValueKind switch
    {
        JsonValueKind.Null => Value.Null,
        JsonValueKind.True => Value.Of(true),
        JsonValueKind.False => Value.Of(false),
        JsonValueKind.String => Value.Of(element.GetString()!),
        JsonValueKind.Number => element.TryGetInt64(out var l) ? Value.Of(l) : Value.Of(element.GetDouble()),
        JsonValueKind.Array => Value.List(element.EnumerateArray().Select(FromElement)),
        JsonValueKind.Object => Value.Map(
            element.EnumerateObject().Select(p => new KeyValuePair<string, Value>(p.Name, FromElement(p.Value)))),
        _ => throw new InvalidOperationException($"unexpected JSON kind: {element.ValueKind}"),
    };

    private static void WriteValue(StringBuilder sb, Value value, int depth)
    {
        switch (value)
        {
            case VNull:
                sb.Append("null");
                break;
            case VBool b:
                sb.Append(b.Bool ? "true" : "false");
                break;
            case VInt i:
                sb.Append(i.Int.ToString(CultureInfo.InvariantCulture));
                break;
            case VFloat f:
                WriteNumber(sb, f.Float);
                break;
            case VString s:
                WriteString(sb, s.Str);
                break;
            case VList l:
                WriteArray(sb, l.Items, depth);
                break;
            case VMap m:
                WriteObject(sb, m.Entries, depth);
                break;
            default:
                throw new InvalidOperationException($"unknown Value: {value.TypeName}");
        }
    }

    private static void WriteObject(StringBuilder sb, ImmutableDictionary<string, Value> map, int depth)
    {
        if (map.IsEmpty)
        {
            sb.Append("{}");
            return;
        }

        // The goldens were generated by JS `sort()` / Java `TreeMap`, which order by
        // UTF-16 code units. StringComparer.Ordinal compares char (UTF-16 code unit)
        // by numeric value — the same ordering.
        var keys = map.Keys.ToArray();
        Array.Sort(keys, StringComparer.Ordinal);

        sb.Append("{\n");
        for (int i = 0; i < keys.Length; i++)
        {
            Indent(sb, depth + 1);
            WriteString(sb, keys[i]);
            sb.Append(": ");
            WriteValue(sb, map[keys[i]], depth + 1);
            if (i + 1 < keys.Length)
            {
                sb.Append(',');
            }

            sb.Append('\n');
        }

        Indent(sb, depth);
        sb.Append('}');
    }

    private static void WriteArray(StringBuilder sb, ImmutableArray<Value> list, int depth)
    {
        if (list.IsEmpty)
        {
            sb.Append("[]");
            return;
        }

        sb.Append("[\n");
        for (int i = 0; i < list.Length; i++)
        {
            Indent(sb, depth + 1);
            WriteValue(sb, list[i], depth + 1);
            if (i + 1 < list.Length)
            {
                sb.Append(',');
            }

            sb.Append('\n');
        }

        Indent(sb, depth);
        sb.Append(']');
    }

    private static void WriteString(StringBuilder sb, string s)
    {
        sb.Append('"');
        foreach (char c in s)
        {
            switch (c)
            {
                case '"':
                    sb.Append("\\\"");
                    break;
                case '\\':
                    sb.Append("\\\\");
                    break;
                case '\n':
                    sb.Append("\\n");
                    break;
                case '\r':
                    sb.Append("\\r");
                    break;
                case '\t':
                    sb.Append("\\t");
                    break;
                case '\b':
                    sb.Append("\\b");
                    break;
                case '\f':
                    sb.Append("\\f");
                    break;
                default:
                    if (c < 0x20)
                    {
                        sb.Append("\\u").Append(((int)c).ToString("x4", CultureInfo.InvariantCulture));
                    }
                    else
                    {
                        // Non-ASCII (and all other) characters are emitted raw.
                        sb.Append(c);
                    }

                    break;
            }
        }

        sb.Append('"');
    }

    private static void WriteNumber(StringBuilder sb, double d)
    {
        // A finite integral double serializes as an integer (matching JS
        // JSON.stringify and the Rust/Java ports).
        if (double.IsFinite(d) && d == Math.Truncate(d))
        {
            sb.Append(((long)d).ToString(CultureInfo.InvariantCulture));
        }
        else
        {
            sb.Append(d.ToString("R", CultureInfo.InvariantCulture));
        }
    }

    private static void Indent(StringBuilder sb, int depth)
    {
        for (int i = 0; i < depth; i++)
        {
            sb.Append("  ");
        }
    }
}
