using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using System.Text.Json;

namespace Varar.Core;

/// <summary>
/// Reads JSON text into the dynamic <see cref="Value"/> model — what the conformance gates use to
/// compare an artifact against a golden by CONTENT rather than by bytes. The golden is one file,
/// generated by the TypeScript reference; key order, indentation and escaping belong to whichever
/// writer produced it, not to the contract.
/// </summary>
public static class JsonValue
{
    /// <summary>
    /// Parses JSON text into a <see cref="Value"/> tree (parsing needs no
    /// canonicalization, so it delegates to <see cref="JsonDocument"/>). Integral
    /// numbers become <see cref="VInt"/>, the rest <see cref="VFloat"/>.
    /// </summary>
    public static Value Parse(string json)
    {
        using var doc = JsonDocument.Parse(json);
        return FromElement(doc.RootElement);
    }

    private static Value FromElement(JsonElement element) => element.ValueKind switch
    {
        JsonValueKind.Null => Value.Null,
        JsonValueKind.True => Value.Of(true),
        JsonValueKind.False => Value.Of(false),
        JsonValueKind.String => Value.Of(element.GetString()!),
        JsonValueKind.Number => element.TryGetInt64(out var l) ? Value.Of(l) : Value.Of(element.GetDouble()),
        JsonValueKind.Array => Value.List(element.EnumerateArray().Select(FromElement)),
        JsonValueKind.Object => Value.Map(
            element.EnumerateObject().Select(p => new KeyValuePair<string, Value>(p.Name, FromElement(p.Value)))),
        _ => throw new InvalidOperationException($"unexpected JSON kind: {element.ValueKind}"),
    };
}
