export type { ParsedArgv } from './argv.ts'
export type { InitOptions, InitResult } from './init.ts'
export type { LintOptions, LintResult } from './lint.ts'
export type { RunOptions, RunResult } from './run.ts'
export const VERSION = '0.0.0'
