package dev.varar.core;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

/**
 * A tiny recursive-descent JSON reader over plain {@code Map}/{@code List}/{@code String}/
 * {@code Number}/{@code Boolean}/{@code null}, plus the normalization the conformance gates compare
 * through.
 *
 * <p>Two callers: {@code varar.lock.json} parsing in {@link Drift}, and every conformance gate,
 * which compares an artifact against a golden by CONTENT rather than by bytes — the golden is one
 * file generated by the TypeScript reference, and key order, indentation and escaping belong to
 * whichever writer produced it, not to the contract.
 */
public final class JsonValue {

    private JsonValue() {}

    /** Parses JSON text; throws {@link IllegalStateException} on malformed input. */
    public static Object parse(String text) {
        return new JsonReader(text).parseWhole();
    }

    /**
     * Puts a parsed golden and a projected artifact into one shape so {@code assertEquals} can
     * compare them: maps sorted (order carries no meaning in JSON), and every integral number a
     * {@code Long}.
     *
     * <p>The number rule is the one the old canonical writer encoded by rendering both an
     * {@code Integer} and a {@code Long} as digits — an artifact holding {@code Integer.valueOf(3)}
     * and a golden parsed as {@code Long.valueOf(3)} say the same thing, and Java's
     * {@code equals} disagrees.
     */
    public static Object normalize(Object value) {
        if (value instanceof Map<?, ?> map) {
            Map<String, Object> out = new TreeMap<>();
            for (Map.Entry<?, ?> entry : map.entrySet()) {
                out.put(String.valueOf(entry.getKey()), normalize(entry.getValue()));
            }
            return out;
        }
        if (value instanceof List<?> list) {
            List<Object> out = new ArrayList<>(list.size());
            for (Object element : list) out.add(normalize(element));
            return out;
        }
        if (value instanceof Double || value instanceof Float) {
            double d = ((Number) value).doubleValue();
            // JSON.stringify prints an integral double without a decimal point, so a golden
            // round-trips it back as an integer — the two must compare equal.
            return d == Math.rint(d) && !Double.isInfinite(d) ? (Object) (long) d : (Object) d;
        }
        if (value instanceof Number number) return number.longValue();
        return value;
    }

    private static final class JsonReader {
        private final String s;
        private int i;

        JsonReader(String s) {
            this.s = s;
        }

        Object parseWhole() {
            Object v = value();
            skipWs();
            if (i != s.length()) throw new IllegalStateException("trailing input");
            return v;
        }

        private Object value() {
            skipWs();
            char c = peek();
            return switch (c) {
                case '{' -> object();
                case '[' -> array();
                case '"' -> string();
                case 't', 'f' -> bool();
                case 'n' -> nul();
                default -> number();
            };
        }

        private Map<String, Object> object() {
            expect('{');
            Map<String, Object> map = new LinkedHashMap<>();
            skipWs();
            if (peek() == '}') {
                i++;
                return map;
            }
            while (true) {
                skipWs();
                String key = string();
                skipWs();
                expect(':');
                map.put(key, value());
                skipWs();
                char c = next();
                if (c == '}') return map;
                if (c != ',') throw new IllegalStateException("expected , or }");
            }
        }

        private List<Object> array() {
            expect('[');
            List<Object> list = new ArrayList<>();
            skipWs();
            if (peek() == ']') {
                i++;
                return list;
            }
            while (true) {
                list.add(value());
                skipWs();
                char c = next();
                if (c == ']') return list;
                if (c != ',') throw new IllegalStateException("expected , or ]");
            }
        }

        private String string() {
            expect('"');
            StringBuilder sb = new StringBuilder();
            while (true) {
                char c = next();
                if (c == '"') return sb.toString();
                if (c == '\\') {
                    char e = next();
                    switch (e) {
                        case '"' -> sb.append('"');
                        case '\\' -> sb.append('\\');
                        case '/' -> sb.append('/');
                        case 'n' -> sb.append('\n');
                        case 'r' -> sb.append('\r');
                        case 't' -> sb.append('\t');
                        case 'b' -> sb.append('\b');
                        case 'f' -> sb.append('\f');
                        case 'u' -> {
                            sb.append((char) Integer.parseInt(s.substring(i, i + 4), 16));
                            i += 4;
                        }
                        default -> throw new IllegalStateException("bad escape");
                    }
                } else {
                    sb.append(c);
                }
            }
        }

        private Object number() {
            int start = i;
            while (i < s.length() && "-+.eE0123456789".indexOf(s.charAt(i)) >= 0) i++;
            String num = s.substring(start, i);
            if (num.isEmpty()) throw new IllegalStateException("expected value");
            if (num.indexOf('.') >= 0 || num.indexOf('e') >= 0 || num.indexOf('E') >= 0) {
                return Double.parseDouble(num);
            }
            return Long.parseLong(num);
        }

        private Boolean bool() {
            if (s.startsWith("true", i)) {
                i += 4;
                return Boolean.TRUE;
            }
            if (s.startsWith("false", i)) {
                i += 5;
                return Boolean.FALSE;
            }
            throw new IllegalStateException("bad literal");
        }

        private Object nul() {
            if (s.startsWith("null", i)) {
                i += 4;
                return null;
            }
            throw new IllegalStateException("bad literal");
        }

        private void skipWs() {
            while (i < s.length()) {
                char c = s.charAt(i);
                if (c == ' ' || c == '\n' || c == '\r' || c == '\t') i++;
                else break;
            }
        }

        private char peek() {
            if (i >= s.length()) throw new IllegalStateException("unexpected end");
            return s.charAt(i);
        }

        private char next() {
            if (i >= s.length()) throw new IllegalStateException("unexpected end");
            return s.charAt(i++);
        }

        private void expect(char c) {
            if (next() != c) throw new IllegalStateException("expected " + c);
        }
    }
}
