using System.IO;
using Varar.Core;
using Xunit;

namespace Varar.Tests;

/// <summary>
/// The <c>trace.json</c> golden gate (T6): for every bundle, executing the plan (with the fixture's
/// initial state) and projecting must reproduce the committed <c>golden/trace.json</c> byte-for-byte.
/// </summary>
public class TraceConformanceTests
{
    public static TheoryData<string> Bundles() => ConformanceFixtures.Bundles();

    [Theory]
    [MemberData(nameof(Bundles))]
    public void TraceMatchesGolden(string bundle)
    {
        var bundleDir = Path.Combine(BundlesDir(), bundle);

        var registry = ConformanceFixtures.Build(bundle);
        var state = ConformanceFixtures.StateFor(bundle);

        var (doc, workspace) = ConformanceFixtures.BundleDocs(bundleDir);
        var plan = Plan.Run(doc, registry, workspace);
        var actual = Conformance.ToTraceArtifact(plan, _ => state());

        // By CONTENT, not bytes: the golden is one file generated by the TypeScript
        // reference, and what a port must agree on is what it says.
        var expected = JsonValue.Parse(File.ReadAllText(Path.Combine(bundleDir, "golden", "trace.json")));
        Assert.Equal(expected, actual);
    }

    private static string BundlesDir() => ConformanceFixtures.BundlesDir();
}
