# frozen_string_literal: true

source "https://rubygems.org"

# During development these resolve against the local monorepo build. The release
# sync (release/targets/70-varar-examples.sh) rewrites them to the published
# versions, e.g. gem "varar-minitest", "~> 0.3".
gem "varar-core", path: "../../ruby/packages/core"
gem "varar", path: "../../ruby/packages/varar"
gem "varar-config", path: "../../ruby/packages/config"
gem "varar-runner", path: "../../ruby/packages/runner"
gem "varar-minitest", path: "../../ruby/packages/minitest"

gem "minitest", "~> 6.0"
gem "rake", "~> 13.0"
