"""Config conformance: every case in conformance/config/cases must parse to
the shared golden, or fail if the case has an expect-error.txt marker. See
conformance/config/README.md.

The comparison is deep equality of the PARSED golden, not of its bytes: the
golden is one file, generated by the TypeScript reference, and what every port
has to agree on is its content — key order, indentation and escaping are the
JSON writer's business, not the contract's."""

import json
from pathlib import Path

import pytest

from varar_config import read_config

# python/packages/config/tests -> parents[4] = repo root
CASES_DIR = Path(__file__).resolve().parents[4] / "conformance" / "config" / "cases"
CASES = sorted(p for p in CASES_DIR.iterdir() if p.is_dir())


def _artifact(cfg) -> dict:
    return {
        "docs": {"include": list(cfg.docs_include), "exclude": list(cfg.docs_exclude)},
        "steps": list(cfg.steps),
        "snippets": dict(cfg.snippets),
    }


@pytest.mark.parametrize("case", CASES, ids=lambda c: c.name)
def test_config_case(case: Path) -> None:
    if (case / "expect-error.txt").exists():
        with pytest.raises(ValueError):
            read_config(case)
    else:
        expected = json.loads((case / "golden.json").read_text(encoding="utf-8"))
        assert _artifact(read_config(case)) == expected
